### ISSUE TITLE
Extension is not working

### ISSUE THREAD

**Issue by sulthanshanid** [jiangnanyouzi/opencart3-stripe-checkout#2]
this extension returns 500 server error when i goto checkout 
i also tried by replacing stripe lib from stripe-php
[11-Sep-2023 05:54:36 UTC] PHP Fatal error:  Uncaught Exception: Error: Could not load model extension/payment/stripe! in /home/eb85h00niowl/storage/modification/system/engine/loader.php:100
Stack trace:
#0 /home/eb85h00niowl/public_html/catalog/model/journal2/checkout.php(443): Loader->model('extension/payme...')
#1 /home/eb85h00niowl/storage/modification/system/engine/loader.php(259): ModelJournal2Checkout->getPaymentMethods()
#2 /home/eb85h00niowl/public_html/system/engine/proxy.php(47): Loader->{closure}(Array, Array)
#3 /home/eb85h00niowl/public_html/catalog/controller/journal2/checkout.php(617): Proxy->__call('getPaymentMetho...', Array)
#4 /home/eb85h00niowl/public_html/catalog/controller/journal2/checkout.php(133): ControllerJournal2Checkout->payment(true)
#5 /home/eb85h00niowl/storage/modification/system/engine/action.php(79): ControllerJournal2Checkout->index()
#6 /home/eb85h00niowl/public_html/system/engine/router.php(59): Action->execute(Object(Registry))
#7 /home/eb85h00niowl/public_html/system/engine/router.php(52): Router->execute(Object( in /home/eb85h00niowl/storage/modification/system/engine/loader.php on line 100
[11-Sep-2023 05:54:37 UTC] PHP Fatal error:  Uncaught Exception: Error: Could not load model extension/payment/stripe! in /home/eb85h00niowl/storage/modification/system/engine/loader.php:100
![Screenshot (198)](https://github.com/jiangnanyouzi/opencart3-stripe-checkout/assets/87685583/e3d310c0-954a-47a7-a476-e947010091ea)
[upload.ocmod.zip](https://github.com/jiangnanyouzi/opencart3-stripe-checkout/files/12572730/upload.ocmod.zip)

**Comment by jiangnanyouzi** [comment]
solved ?

**Comment by sulthanshanid** [comment]
no sir
